### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Gyrofalcon** [Rfvgyhn/gwent-tracker#9]
1) Under column for "Copies" can we have obtainable number of copies? Ex : Decoy 3/3 (got all 3 of them) and Scorch 2/3 (have one left to find/obtain)

2) Any plans to implement DLC Heart of Stones card?  I see the Leaders, but cards like Cow or Toad are not in the list

3) Is it possible for you program to know what version of example "Impera Brigade Guard" when the deck only has 3 copies out of 4? To help track down the missing cards.

**Comment by rfvgyhn** [comment]
1. Good idea. Will be in the next release.
2. Will be fixed in the next release.
3. The save file only provides the number of copies obtained as an integer. If I knew where gwent specific quests, containers and npcs were stored in the save file, it would be do-able. That's a large amount of work though and I doubt I will get to it.
